version: "3.1"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: muhammad
      POSTGRES_DB: todo
    ports:
      - 5432:5432